In [1]:
""" 1. 333신경망 """
import numpy as np

def sigmoid(x):
    return 1/(1 + np.exp(-x))

I = np.array([0.9, 0.1, 0.8], ndmin=2).T
W_input_hidden = np.array([[0.9, 0.2, 0.1],
                         [0.3, 0.8, 0.5],
                         [0.4, 0.2, 0.6]]).T

W_hidden_output = np.array([[0.3, 0.6, 0.8],
                           [0.7, 0.5, 0.1],
                           [0.5, 0.2, 0.9]]).T

X_hidden = np.dot(W_input_hidden, I)
O_hidden = sigmoid(X_hidden)
X_output = np.dot(W_hidden_output, O_hidden)
O_output = sigmoid(X_output)
print(O_output)

[[0.72630335]
 [0.70859807]
 [0.77809706]]


In [2]:
""" 2. 222신경망 """

W_hidden_output = np.array([[2,1],
                           [3,4]],ndmin=2).T
e_output_1 = 0.8
e_output_2 = 0.5

e_hidden_1 = (e_output_1*(W_hidden_output[0][0]/(W_hidden_output[0][0]+W_hidden_output[0][1]))) + (e_output_2*(W_hidden_output[1][0]/(W_hidden_output[1][0]+W_hidden_output[1][1])))
e_hidden_2 = (e_output_1*(W_hidden_output[0][1]/(W_hidden_output[0][0]+W_hidden_output[0][1]))) + (e_output_2*(W_hidden_output[1][1]/(W_hidden_output[1][0]+W_hidden_output[1][1])))

print(e_hidden_1)
print(e_hidden_2)

0.42000000000000004
0.88


In [3]:
""" 3. 222신경망 """

o_j = np.array([0.4, 0.5],ndmin=2).T
w = np.array([[2, 1],  
            [3, 4]]).T

w_o_ = np.dot(w, o_j) # 시그모이드 함수내의 합

alpha = 0.1 # 가중치
e_1 = 0.8   # 오차 e1


print('e1:', e_1)
print('sigmoid(w_o_[0]):', sigmoid(w_o_[0]))
print('1 - sigmoid(w_o_[0]):', 1- sigmoid(w_o_[0]))
print('o_j:', o_j[0])
print('오차기울기:', -0.8*0.909*(1-0.909)*0.4)
print('변화량:', alpha*-0.8*0.909*(1-0.909)*0.4)
print('===========================================')
print('새로운 w11:', 2 - alpha*-0.8*0.909*(1-0.909)*0.4)

e1: 0.8
sigmoid(w_o_[0]): [0.90887704]
1 - sigmoid(w_o_[0]): [0.09112296]
o_j: [0.4]
오차기울기: -0.026470079999999997
변화량: -0.002647008
새로운 w11: 2.002647008


In [21]:
""" 4. 333신경망 > 역전파 오차값과 가중치 업데이트를 계산해 보세요."""
targets = np.array([[0.01], [0.01], [0.99]])
W_hidden_output = np.array([[0.3, 0.6, 0.8],
                           [0.7, 0.5, 0.1],
                           [0.5, 0.2, 0.9]]).T
alpha = 0.1 # 학습률

# 오차값(절대값)
# | targets - O_output|
e_output = np.array([0.716, 0.698, 0.212])

# 역전파 가중치는 정규화
e_hidden_output_1 = e_output[0]*W_hidden_output[0][0] + e_output[1]*W_hidden_output[0][1] + e_output[2]*W_hidden_output[0][2]
e_hidden_output_2 = e_output[0]*W_hidden_output[1][0] + e_output[1]*W_hidden_output[1][1] + e_output[2]*W_hidden_output[1][2]
e_hidden_output_3 = e_output[0]*W_hidden_output[2][0] + e_output[1]*W_hidden_output[2][1] + e_output[2]*W_hidden_output[2][2]

print('*역전파 오차값 ')
print('e_hidden_output1:',e_hidden_output_1)
print('e_hidden_output2:',e_hidden_output_2)
print('e_hidden_output3:',e_hidden_output_3)
print('===========================================')


# 가중치 업데이트
print('*가중치 업데이트(은닉계층-출력계층)')
O_hidden = np.array([0.761, 0.603, 0.65])
sigma_wo = np.dot(W_hidden_output, O_hidden)

# 오차기울기
k_1 = -e_output[0]*sigmoid(sigma_wo[0])*(1-sigmoid(sigma_wo[0]))*O_hidden[0]  # 첫번째 오차기울기
k_2 = -e_output[1]*sigmoid(sigma_wo[1])*(1-sigmoid(sigma_wo[1]))*O_hidden[1]  # 두번째 오차기울기
k_3 = -e_output[2]*sigmoid(sigma_wo[2])*(1-sigmoid(sigma_wo[2]))*O_hidden[2]  # 세번째 오차기울기


print('새로운 가중치 w11 :', W_hidden_output[0][0]-alpha*k_1)
print('새로운 가중치 w12 :', W_hidden_output[1][0]-alpha*k_2)
print('새로운 가중치 w13 :', W_hidden_output[2][0]-alpha*k_3)
print('새로운 가중치 w21 :', W_hidden_output[0][1]-alpha*k_1)
print('새로운 가중치 w22 :', W_hidden_output[1][1]-alpha*k_2)
print('새로운 가중치 w23 :', W_hidden_output[2][1]-alpha*k_3)
print('새로운 가중치 w31 :', W_hidden_output[0][2]-alpha*k_1)
print('새로운 가중치 w32 :', W_hidden_output[1][2]-alpha*k_2)
print('새로운 가중치 w33 :', W_hidden_output[2][2]-alpha*k_3)
print('===========================================')
print('*가중치 비교')
print(W_hidden_output)
new_W_hidden_output = np.array([[W_hidden_output[0][0]-alpha*k_1, W_hidden_output[1][0]-alpha*k_2, W_hidden_output[2][0]-alpha*k_3],
                               [W_hidden_output[0][1]-alpha*k_1, W_hidden_output[1][1]-alpha*k_2, W_hidden_output[2][1]-alpha*k_3],
                               [W_hidden_output[0][2]-alpha*k_1, W_hidden_output[1][2]-alpha*k_2, W_hidden_output[2][2]-alpha*k_3]],ndmin=2).T
print(new_W_hidden_output)

*역전파 오차값 
e_hidden_output1: 0.8093999999999999
e_hidden_output2: 0.821
e_hidden_output3: 0.8333999999999999
*가중치 업데이트(은닉계층-출력계층)
새로운 가중치 w11 : 0.3108340984944785
새로운 가중치 w12 : 0.6086926655223571
새로운 가중치 w13 : 0.8023799591801705
새로운 가중치 w21 : 0.7108340984944784
새로운 가중치 w22 : 0.5086926655223571
새로운 가중치 w23 : 0.10237995918017039
새로운 가중치 w31 : 0.5108340984944785
새로운 가중치 w32 : 0.20869266552235713
새로운 가중치 w33 : 0.9023799591801704
*가중치 비교
[[0.3 0.7 0.5]
 [0.6 0.5 0.2]
 [0.8 0.1 0.9]]
[[0.3108341  0.7108341  0.5108341 ]
 [0.60869267 0.50869267 0.20869267]
 [0.80237996 0.10237996 0.90237996]]
